name: Publish-GetLicenseInfo
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**'
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "publishToGallery"
  publishToGallery:
    # The type of runner that the job will run on
    runs-on: windows-latest
    env: 
      MODULE_NAME: GetLicenseInfo

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v4

    - name: Build module
      shell: pwsh
      run: |
        $moduleName = $env:MODULE_NAME
        Copy-Item -Path "$env:GITHUB_WORKSPACE\LICENSE" -Destination "$env:GITHUB_WORKSPACE\Module\$moduleName\LICENSE.txt" -Force
        "Building module"
        &"$env:GITHUB_WORKSPACE\Workflow\BuildModule.ps1" -RootPath "$env:GITHUB_WORKSPACE" -ModuleName $moduleName
        - name: Install AzureSignTool
        run:  dotnet tool install --global AzureSignTool
   
    - name: Install AzureSignTool
      run:  dotnet tool install --global AzureSignTool

    - name: Sign files
      shell: pwsh
      run: |
        $files = Get-ChildItem "$env:GITHUB_WORKSPACE\Module\$env:MODULE_NAME" -File -Recurse -Include *.ps1, *.ps1xml, *.psd1, *.psm1, *.pssc, *.psrc, *.cdxml, *.dll
        try {
            foreach ($file in $files) {
                azuresigntool sign `
                    -kvu ${{ vars.CODESIGNING_KEYVAULTURI }} `
                    -kvi ${{ vars.TENANTINTEGRATION_CLIENTID }} `
                    -kvt ${{ vars.TENANTINTEGRATION_TENANTID }} `
                    -kvs ${{ secrets.TENANTINTEGRATION_CLIENTSECRET }} `
                    -kvc ${{ vars.CODESIGNING_CERTNAME }} `
                    -tr 'http://timestamp.digicert.com' `
                    -v "$($file.FullName)" 
            }
        }
        catch {
            Write-Host "Error: $($_.Exception)"
            throw
        }
        Write-Host "Signed files summary:"
        Get-AuthenticodeSignature -FilePath $files

    - name: Publish
      #Publish to PS Gallery
      shell: pwsh
      if: ${{ github.event_name != 'workflow_dispatch' }}
      env:
        SECRET: ${{ secrets.GC_PSGALLERY_APIKEY }}
      run: |
        write-host "Publishing from: $env:GITHUB_WORKSPACE\Module\$env:MODULE_NAME"
        try
        {
          $env:PSModulePath = "$env:PSModulePath;$env:GITHUB_WORKSPACE\Module"
          "PSModulePath: $env:PSModulePath"
          Publish-Module -Path "$env:GITHUB_WORKSPACE\Module\$env:MODULE_NAME" -NuGetApiKey "$env:SECRET"
        }
        catch
        {
          Write-Host "Error: $($_.Exception)"
          throw
        }
  